{% set version = "0.41.1" %}

package:
  name: wheel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/wheel/wheel-{{ version }}.tar.gz
  sha256: 12b911f083e876e10c595779709f8a88a59f45aacc646492a67fe9ef796c1b47

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -c "import flit_core.buildapi; flit_core.buildapi.build_wheel('.')" && {{ PYTHON }} -m installer --no-compile-bytecode wheel-*.whl
  entry_points:
    - wheel = wheel.cli:main

requirements:
  host:
    - flit-core
    - python >=3.7
    - python-installer
  run:
    - python >=3.7

test:
  imports:
    - wheel
    - wheel.cli
  commands:
    - pip check
    - wheel --help
  requires:
    - pip

about:
  home: https://github.com/pypa/wheel
  license: MIT
  license_file: LICENSE.txt
  summary: A built-package format for Python.

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - ocefpaf
    - mingwandroid
